### ISSUE TITLE
A good companion to Ubiquits?

### ISSUE THREAD

**Issue by zakhenry** [pleerock/typeorm#10]
Hey, just came across Typeorm and was wondering if it would be a good fit for the TS framework I'm building over at http://github.com/ubiquits/ubiquits or http://ubiquits.com? I'm still in early stage development - intending to release developer preview next week and am currently building on Sequelize, but it looks like Typeorm might be an easier implementation.

Also regarding your issue on the need to build a documentation site, you might want to consider the infrastructure I've built up to document Ubiquits

**Comment by pleerock** [comment]
Hello, it totally should be. Any good framework must came with a good ORM. And typeorm can play a good role in your stack. And yeah, its also in active development, like your framework. I was also working on a [framework](https://github.com/pleerock/microframework), but its not a fullstack (and will not be, initially i was planning to do it for rest microservices, and I'm using it internally on some of my projects). Any framework should compose of components, like DI, routing, validation, etc. If you are interesting you can also think about using [typedi](https://github.com/pleerock/typedi) and [routing-controllers](https://github.com/pleerock/routing-controllers). There is also [validation component](https://github.com/pleerock/class-validator). Take a look on my other open source projects in my repositories, maybe you'll find something more that you can use in your framework.

What about documentation site  - I'll think about it, but I would like to build it on something very simple and I want to write all documentation in markdown (maybe jekyll, don't know yet)

**Comment by pleerock** [comment]
There is also [typeodm](https://github.com/pleerock/typeodm) I was working on, but right now my focus only on ORM - after I finish all my todos and it will stabilize, so I can publish it to public, I'll switch to typeodm. There is no documentation there, however take a look on [samples](https://github.com/pleerock/typeodm/tree/master/sample) and you'll see that its a good db framework too

**Comment by zakhenry** [comment]
Awesome, I'll see about migrating over from Sequelize. I see the note in the readme about Postgres not being quite finished, what is missing? I want to use Postgres for the uuid & json column types, and schemas. I'm happy to fork and add this functionality if it's missing.

**Comment by zakhenry** [comment]
Regarding the framework stuff, yea I really like what you are doing with those components - I'm planning to use the class validation one already. With DI, I've already built that, leveraging the `@angular/core/di` components so the service provider and testing framework all work the same as angular2.

On documentation, the toolchain I've built up is pretty close to a clone of Jekyll - all docs are markdown with yaml frontmatter defining metadata. See the https://github.com/ubiquits/ubiquits/tree/master/docs directory for the source. I considered using Jekyll, but wanted to be able to have file watchers running on both the site and documentation simultaneously, all using node as I haven't used Ruby before.

**Comment by pleerock** [comment]
> Awesome, I'll see about migrating over from Sequelize. I see the note in the readme about Postgres not being quite finished, what is missing? I want to use Postgres for the uuid & json column types, and schemas. I'm happy to fork and add this functionality if it's missing.

For postgres unfortunately almost nothing is working yet, I just started to work on it, but switched to other tasks. If you want to contribute - then almost all you need is this: [PostgresSchemaBuilder](https://github.com/pleerock/typeorm/blob/master/src/schema-builder/PostgresSchemaBuilder.ts) . Its copy-pasted version of MysqlSchemaBuilder, with some changes to fit postgres. But its completed only on 5% =(. Driver abstraction is far away from perfect yet, but its possible to integrate it with postgres.

>  On documentation, the toolchain I've built up is pretty close to a clone of Jekyll - all docs are markdown with yaml frontmatter defining metadata. See the https://github.com/ubiquits/ubiquits/tree/master/docs directory for the source. I considered using Jekyll, but wanted to be able to have file watchers running on both the site and documentation simultaneously, all using node as I haven't used Ruby before.

Right now site is not a priority for me, I have lot of other tasks. If someone decide to contribute and take this pain from me - would be great. I'll think about ubiquits, but one thing about Jekyll is that it generates static html, generates sitemap, all other out of box small features + the main is that it can be hosted on github. The bad side, of course is that its a Ruby.
